CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   PERIOD         CHAR(50)     NOT NULL,
   BEGINING        CHAR(50),
   CONCLUSION		char(50),
   APPROXIMATEDATE	CHAR(50),
   SALARY         REAL
);
